### PR TITLE
uncompress needed before extracting

### PR DESCRIPTION
**Pull request by tst2005**

### CODE REVIEW

**Comment by travier-anssi** [comment]
Thanks for the suggestion. The 'x' extract switch should however already perform the zstd decompression. Can you tell us which distribution and version of tar you are using?

**Comment by tst2005** [comment]
I'm using tar (GNU tar) 1.29 on Debian GNU/Linux 9.11 (stretch,oldstable) on amd64.


Another minor thing...

It is not the bsd tar so I also got lot of warnings :
```
tar: Ignoring unknown extended header keyword `SCHILY.fflags' 
```
This issue seems known and not important (See https://github.com/doitsujin/dxvk/issues/117).

**Comment by travier-anssi** [comment]
> I'm using tar (GNU tar) 1.29 on Debian GNU/Linux 9.11 (stretch,oldstable) on amd64.

We do not support older Debian releases so we will keep the instructions as is for now (and you have found a simple workaround).

> tar: Ignoring unknown extended header keyword `SCHILY.fflags'

You can use `--warning=no-unknown-keyword` to ignore those.

Thanks for the report.

**Comment by tst2005** [comment]
You're welcome!

**Pull request closed without merging**
